### ISSUE TITLE
issue installing on ubuntu 20.04.1

### ISSUE THREAD

**Issue by thedxt** [45Drives/cockpit-hardware#11]
when installing on fresh install of ubuntu 20.04.1 after adding the 45drives.list `sudo apt update` will fail.

The error is 

```
user@ubuntu-test:/etc/apt/sources.list.d$ sudo apt update
Hit:1 http://ca.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://images.45drives.com/repo/debian focal InRelease [1,778 B]
Hit:3 http://ca.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://ca.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Err:2 http://images.45drives.com/repo/debian focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9AAA9122CACDEF2C
Reading package lists... Done
W: GPG error: http://images.45drives.com/repo/debian focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9AAA9122CACDEF2C
E: The repository 'http://images.45drives.com/repo/debian focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

a workaround is to run `sudo apt update --allow-insecure-repositories` instead. After that everything works.

**Comment by bkelly16** [comment]
You need to also import the GPG key after adding the spt source .list file.
Readme has been updated.
`wget -qO - http://images.45drives.com/repo/keys/aptpubkey.asc | apt-key add -`

**Comment by thedxt** [comment]
thanks

**Comment by thedxt** [comment]
that cleared up the issue but created another one.

when running apt update I get the following error

`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://images.45drives.com/repo/debian focal InRelease' doesn't support architecture 'i386'`

**Comment by markdhooper** [comment]
We've since moved our repo server to [repo.45drives.com](https://repo.45drives.com).
There is a setup script there to automatically configure our repos.
