### ISSUE TITLE
Feature Request: Easier to add other servers  and configs

### ISSUE THREAD

**Issue by Trinity93** [45Drives/cockpit-hardware#14]
Would be nice if this could be used on say a dell server. If the hardware detection used some sort of component db this would be easier to accomplish and would have the benefit of allowing this plugin to be used more widely as well as allowing you to do more custom configs in your hardware.

**Comment by markdhooper** [comment]
This package (cockpit-45drives-hardware) is inexorably linked to our hardware. The way we serialize our units is the only way in some cases to distinguish one of our server models from another.  Though this matters more for the 45Drives-system and 45Drives-disks modules moreso than the 45Drives-motherboard module.

In terms of components, making the assets is by far the most time consuming part of these modules. It's enough work for me to just keep up with our own server models/components. 

By all means, if you want to fork the repo, this is all open-source, and you have my blessing, and I can help explain how it all works as of now. But the way that I wrote it truly will not scale in the way you're proposing.
