### ISSUE TITLE
Support for the 45HomeLab HL15

### ISSUE THREAD

**Issue by 0r1x** [45Drives/cockpit-hardware#24]
X11SPH-nCTPF

Output from the pre-install on the full build option:

Unsupported Motherboard Model Detected
Motherboard Detected:
X11SPH-nCTPF
Support for X11SPH-nCTPF is not available at this time.

**Comment by pcpcoreyster** [comment]
To help give more clarification details to the pre-build/pre-install HL-15 -Fully Built & Burned In  package the following error is encountered for the cockpit left navigation pane label "45Drives Motherboard" as Or1x denoted "Unsupported Motherboard Model Detected".

I have a screenshot attached
![hl15-prebuilt-45drives-motherboard-error](https://github.com/45Drives/cockpit-hardware/assets/60240578/c7561808-7e44-401c-a074-d6450f1dd93a).

The error is displayed after the "Gathering Information" has green checkmarks for:
- SATA
- RAM
- Network Devices

The motherboard & CPU do not finish with a green checkmark.   The attached image is displayed. 
 
The installed packages are from @45drives_stable:
45drives-tools.x86_64                      3.0.2-1.el8                                                @45drives_stable
cockpit-45drives-hardware.noarch           2.3.4-1.el8                                                @45drives_stable
cockpit-benchmark.noarch                   2.1.0-2.el8                                                @45drives_stable
cockpit-file-sharing.noarch                3.3.4-1.el8                                                @45drives_stable
cockpit-identities.noarch                  0.1.12-1.el8                                               @45drives_stable
cockpit-navigator.noarch                   0.5.10-1.el8                                               @45drives_stable
cockpit-packagekit.noarch                  250.1.1-1.el8                                              @45drives_stable
cockpit-pcp.x86_64                         250.1.1-1.el8                                              @45drives_stable
cockpit-storaged.noarch                    250.1.1-1.el8                                              @45drives_stable
cockpit-zfs-manager.noarch                 1.3.1-1.el8                                                @45drives_stable
libldb.x86_64                              2.7.2-3.el8                                                @45drives_stable
libnetapi.x86_64                           4.18.6-2.el8_9                                             @45drives_stable
libsmbclient.x86_64                        4.18.6-2.el8_9                                             @45drives_stable
libtalloc.x86_64                           2.4.0-3.el8                                                @45drives_stable
libwbclient.x86_64                         4.18.6-2.el8_9                                             @45drives_stable
python3-ldb.x86_64                         2.7.2-3.el8                                                @45drives_stable
python3-samba.x86_64                       4.18.6-2.el8_9                                             @45drives_stable
python3-samba-dc.x86_64                    4.18.6-2.el8_9                                             @45drives_stable
python3-talloc.x86_64                      2.4.0-3.el8                                                @45drives_stable
samba.x86_64                               4.18.6-2.el8_9                                             @45drives_stable
samba-client-libs.x86_64                   4.18.6-2.el8_9                                             @45drives_stable
samba-common.noarch                        4.18.6-2.el8_9                                             @45drives_stable
samba-common-libs.x86_64                   4.18.6-2.el8_9                                             @45drives_stable
samba-common-tools.x86_64                  4.18.6-2.el8_9                                             @45drives_stable
samba-dc-libs.x86_64                       4.18.6-2.el8_9                                             @45drives_stable
samba-dcerpc.x86_64                        4.18.6-2.el8_9                                             @45drives_stable
samba-ldb-ldap-modules.x86_64              4.18.6-2.el8_9                                             @45drives_stable
samba-libs.x86_64                          4.18.6-2.el8_9                                             @45drives_stable
samba-tools.x86_64                         4.18.6-2.el8_9                                             @45drives_stable
samba-winbind.x86_64                       4.18.6-2.el8_9                                             @45drives_stable
samba-winbind-clients.x86_64               4.18.6-2.el8_9                                             @45drives_stable
samba-winbind-modules.x86_64               4.18.6-2.el8_9                                             @45drives_stable
serial45d.x86_64                           3.0.1-1.el8                                                @45drives_stable
znapzend.x86_64                            0.21.0-1.el8                                               @45drives_stable

I do see the commits within the repository denoting the updates for the cockpit left navigation "45Drives Disk" and "45Drives System". 

I noticed in the helper_script/motherboard the HL15 prebuilt motherboards --  X11SPH-nCTPF (2x 10Gbps SFP+ model) or X11SPH-nCTF (2x 10Gbps RJ45 model) -- are not included in g_dmi_mobo_fields.  

The CPU (Intel Xeon Bronze 3204) shipped with the unit is not included.    The value that would be captured by dmidecode would be 

> Intel(R) Xeon(R) Bronze 3204 CPU @ 1.90GHz

**Comment by MrVassallo** [comment]
This appears to be fixed. The readme of the github page includes these motherboards now and my fresh install has the board displaying.

Just putting a post here to say I believe this is completed/fixed even though the status still says it's open.

**Comment by pcoreyster** [comment]
Will check that out today - try to have my HL-15 check for an update
